CREATE DATABASE REBORN_TECHNOLOGY

CREATE TABLE EMPLEADO_REBORN_TECHNOLOGY (
DNI VARCHAR (15) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
TELEFONO VARCHAR (15) NOT NULL,
DEPARTAMENTO VARCHAR (15) NOT NULL,
SUELDO FLOAT (6) NOT NULL,
DIRECCION VARCHAR (30) NOT NULL,
HIJOS INT (2),
FECHA_COMIENZO DATE
);

CREATE TABLE EMPLEADO_Jorge_REBORN_TECHNOLOGY (
DNI VARCHAR (15) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
TELEFONO VARCHAR (15) NOT NULL,
DEPARTAMENTO VARCHAR (15) NOT NULL,
SUELDO FLOAT (6) NOT NULL,
DIRECCION VARCHAR (30) NOT NULL,
HIJOS INT (1),
FECHA_COMIENZO DATE
);

CREATE TABLE EMPLEADO_Michael_REBORN_TECHNOLOGY (
DNI VARCHAR (15) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
TELEFONO VARCHAR (15) NOT NULL,
DEPARTAMENTO VARCHAR (15) NOT NULL,
SUELDO FLOAT (6) NOT NULL,
DIRECCION VARCHAR (30) NOT NULL,
HIJOS INT (2),
FECHA_COMIENZO DATE
);

CREATE TABLE EMPLEADO_Pilar_REBORN_TECHNOLOGY (
DNI VARCHAR (15) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
TELEFONO VARCHAR (15) NOT NULL,
DEPARTAMENTO VARCHAR (15) NOT NULL,
SUELDO FLOAT (6) NOT NULL,
DIRECCION VARCHAR (30) NOT NULL,
HIJOS INT (4),
FECHA_COMIENZO DATE
);

CREATE TABLE EMPLEADO_Laura_REBORN_TECHNOLOGY (
DNI VARCHAR (15) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
TELEFONO VARCHAR (15) NOT NULL,
DEPARTAMENTO VARCHAR (15) NOT NULL,
SUELDO FLOAT (6) NOT NULL,
DIRECCION VARCHAR (30) NOT NULL,
HIJOS INT (3),
FECHA_COMIENZO DATE
);

-- INSERT INTO

-- INSERT INTO + nombreTABLA + (nombreCAMPOS) + VALUES + (REGISTROS);

-- INSERT INTO empleado_reborn_technology (DNI, NOMBRE, TELEFONO, DEPARTAMENTO, SUELDO, DIRECCION, HIJOS, FECHA_COMIENZO) VALUES ('560002420P', 'Manuel', '618797889', 'Informatica', 1850, 'Calle arroyo de la niñera', 2, '2024/10/06');


-- INSERT INTO

-- INSERT INTO + nombreTABLA + (nombreCAMPOS) + VALUES + (REGISTROS);

-- INSERT INTO empleado_jorge_reborn_technology (DNI, NOMBRE, TELEFONO, DEPARTAMENTO, SUELDO, DIRECCION, HIJOS, FECHA_COMIENZO) VALUES ('981256574P', 'Jorge', '698341768', 'Informatica', 1800, 'Calle Señorio de la sal', 1, '2024/11/05');


-- INSERT INTO

-- INSERT INTO + nombreTABLA + (nombreCAMPOS) + VALUES + (REGISTROS);

-- INSERT INTO empleado_michael_reborn_technology (DNI, NOMBRE, TELEFONO, DEPARTAMENTO, SUELDO, DIRECCION, HIJOS, FECHA_COMIENZO) VALUES ('123980298J', 'Michael', '601657894', 'Finanzas', 2000, 'Calle Caserio Colesterol', 2, '2024-01-25');


-- INSERT INTO

-- INSERT INTO + nombreTABLA + (nombreCAMPOS) + VALUES + (REGISTROS);

-- INSERT INTO empleado_pilar_reborn_technology (DNI, NOMBRE, TELEFONO, DEPARTAMENTO, SUELDO, DIRECCION, HIJOS, FECHA_COMIENZO) VALUES ('198209365L', 'Pilar', '638490128', 'Finanzas', 2000, 'Calle oasis ostentoso', 4, '2024-05-03');


-- INSERT INTO

-- INSERT INTO + nombreTABLA + (nombreCAMPOS) + VALUES + (REGISTROS);

-- INSERT INTO empleado_laura_reborn_technology (DNI, NOMBRE, TELEFONO, DEPARTAMENTO, SUELDO, DIRECCION, HIJOS, FECHA_COMIENZO) VALUES ('934678009L', 'Laura', '698247589', 'Marketing', 2000, 'Calle Ribera repipi', 3, '2024-03-10');







